sudo: required
dist: trusty # ubuntu 14.04.5 LTS
language: python

# if specific version(s) of docker or docker-compose needed, see travis-CI docs online
services:
  - docker # default is most recent docker and docker-compose versions

install:
  - docker pull mysql:5.7.14
  - mkdir db
  - >
    docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS'
    -v ~/db:/var/lib/mysql mysql:5.7.14
  - sleep 10 # need to give time for mysql to start
  - >
    docker run -it --name mysql-cmd --rm --link mysql:db mysql:5.7.14
    mysql -uroot -p'$3cureUS' -h db -v -e
    "CREATE DATABASE cs4501 CHARACTER SET utf8;
    CREATE DATABASE test_cs4501 CHARACTER SET utf8;
    CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';
    GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"

before_script:
  - docker-compose up -d

script: 
  - >
    docker exec -it models bash -c
    "pip install -r requirements.txt &&
    python manage.py loaddata db.json &&
    python manage.py test --noinput" # run Django unit tests on models

after_script:
  - docker-compose stop
  - docker stop mysql
  - docker rm `docker ps -a -q`
  - docker rmi `docker images -q`
