sudo: required
dist: trusty # google-cloud-engine mod of ubuntu 14.04.3 LTS
language: python
python:
  - "3.5"

# if specific versions of docker or docker-compose are needed, see travis-CI docs
services:
  - docker # default is docker 1.8.2 and docker-compose 1.4.2 (as of Oct. 2016)

install: # prepare mySQL database
  - docker pull mysql:5.7.14
  - mkdir db
  - >
    docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS'
    -v `pwd`/db:/var/lib/mysql mysql:5.7.14
  - sleep 10 # need to give time for mysql to start
  - >
    docker run -it --name mysql-cmd --rm --link mysql:db mysql:5.7.14
    mysql -uroot -p'$3cureUS' -h db -v -e
    "CREATE DATABASE cs4501 CHARACTER SET utf8;
    CREATE DATABASE test_cs4501 CHARACTER SET utf8;
    CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';
    GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
  - sudo pip install coveralls
before_script:
  - docker-compose up -d

script:
  - >
    docker exec -it models bash -c
    "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH &&
    export PYTHONPATH=. &&
    pip install -r requirements.txt &&
    pip install coveralls && 
    pip install django_coverage && 
    python manage.py test --with-coverage --noinput && cat .coverage" # run Django unit tests on models
  # can put other tests (e.g. integrations) here too with exp, web containers

after_success: 
  - ls models/*
  - cat models/.coverage
  - sed -i "s/\/app\///g" models/.coverage 
  - cat models/.coverage
  - cd models
  - coveralls
  #- cp models/.coverage .
  #- mkdir app
  #- mkdir app/models
  #- mkdir app/daasapp
  #- mkdir app/daasapp/tests/
  #- docker cp models:/app/.coverage .
  #- docker cp models:/app/daasapp/__init__.py app/daasapp/
  #- docker cp models:/app/daasapp/err_models.py app/daasapp/
  #- docker cp models:/app/daasapp/models.py app/daasapp/
  #- docker cp models:/app/daasapp/tests/__init__.py app/daasapp/tests/
  #- docker cp models:/app/daasapp/tests/test_drones.py app/daasapp/tests/
  #- docker cp models:/app/daasapp/tests/test_listing.py app/daasapp/tests/
  #- docker cp models:/app/daasapp/tests/test_users.py app/daasapp/tests/
  #- docker cp models:/app/daasapp/views.py app/daasapp/
  #- docker cp models:/app/daasapp/manage.py app/daasapp/
  #- docker cp models:/app/models/__init__.py app/models/
  #- docker cp models:/app/models/apiposts.py app/models/
  #- docker cp models:/app/models/home.py app/models/
  #- docker cp models:/app/models/settings.py app/models/
  #- docker cp models:/app/models/urls.py app/models/
  #- docker exec -it models bash -c "coveralls"
  #- coveralls

after_script:
  - docker-compose stop
  - docker stop mysql
  - docker rm `docker ps -a -q`
  - docker rmi `docker images -q`
  - rm -rf db
