models: # PORT 8002
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models/:/app
    ports:
      - "8002:8000"
    command: bash -c "pip install faker --upgrade && python manage.py makemigrations && python manage.py migrate && pip install --upgrade requests && pip install --upgrade urllib3 && pip install arrow --upgrade && python manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"

exp: # PORT 8001
    image: tp33/django
    links:
      -  models:models-api
    volumes:
      - ./exp/:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
web: # PORT 8000
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./web/:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install whitenoise --upgrade && pip install arrow --upgrade && python manage.py collectstatic --noinput && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"
