models: # PORT 8002
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models/:/app
    ports:
      - "8002:8000"
    command: bash -c "python /app/manage.py migrate && python /app/manage.py makemigrations && pip install --upgrade requests && pip install --upgrade urllib3 && python /app/manage.py loaddata /app/db.json && mod_wsgi-express start-server --reload-on-changes /app/models/wsgi.py"

exp: # PORT 8001
    image: tp33/django
    links:
      -  models:models-api
    volumes:
      - ./exp/:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"
web: # PORT 8000
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./web/:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install whitenoise --upgrade && python manage.py collectstatic --noinput && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"
