models: # PORT 8002
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models/:/app
    ports:
      - "8002:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./models/wsgi.py"
    container_name: models

exp: # PORT 8001
    image: tp33/django
    external_links:
      -  mysql:db
    links:
      - models:models-api
      - kafka:kafka
      - es:es
    volumes:
      - ./exp/:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install -r requirements.txt && mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"
    container_name: exp

web: # PORT 8000
    image: tp33/django
    links:
      -  exp:exp-api
      -  selenium
    volumes:
      - ./web/:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py collectstatic --noinput && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py && python manage.py test"
    container_name: web
    environment:
      - SELENIUM_HOST=http://selenium:4444/wd/hub
      - TEST_SELENIUM='yest'

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   command: bash -c "sleep 30 && echo 'kafka queueing' && python es_index.py"
   volumes:
      - ./batch/:/app

selenium:
    image: selenium/standalone-chrome:2.48.2
    ports:
      -  "5900:5900"