models: # PORT 8002
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./models/:/app
    ports:
      - "8002:8000"
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID
      - GIT_DISCOVERY_ACROSS_FILESYSTEM
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./models/wsgi.py"
    container_name: models

exp: # PORT 8001
    image: tp33/django
    links:
      -  models:models-api
    volumes:
      - ./exp/:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install -r requirements.txt && mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"
    container_name: exp

web: # PORT 8000
    image: tp33/django
    links:
      -  exp:exp-api
    volumes:
      - ./web/:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py collectstatic --noinput && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"
    container_name: web
