DROP DATABASE IF EXISTS `cs4501`;
CREATE DATABASE `cs4501`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 'mysql';
GRANT ALL PRIVILEGES ON cs4501.* TO 'www'@'%' IDENTIFIED BY '$3cureUS'

WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS `test_cs4501`;
CREATE DATABASE `test_cs4501`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 'mysql';
GRANT ALL PRIVILEGES ON test_cs4501.* TO 'www'@'%' IDENTIFIED BY '$3cureUS'

WITH GRANT OPTION;
FLUSH PRIVILEGES;
